# prettier-ignore
version: '3'
services:
  web:
    build: .
    container_name: "myapp"
    ports: 
      - "80:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongo"
    ports: 
      - "27017:27017"
