# prettier-ignore
version: '3'
services:
  web:
    build: .
    container_name: "myapp"
    depends_on:
      - mongodb
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - ./data/db:/data/db
    ports: 
      - "27017:27017"
